### ISSUE TITLE
Enhance UI of landing page aceternity globe component

### ISSUE THREAD

**Issue by akadeepesh** [akadeepesh/OIBSIP#2]
This is a pizza selling web app, I need to enhance the UI of this globe below accordingly. 

![image](https://github.com/user-attachments/assets/118d0548-c160-40a9-a185-eae39a9464f4)

You can access component at `pizza-delivery-app-client/components/PizzaGlobeLanding.tsx`

**Comment by MVENKATESH786** [comment]
I want to work on this issue please assign me.

**Comment by akadeepesh** [comment]
> I want to work on this issue please assign me.

Go ahead @MVENKATESH786. Assigned.

**Comment by akadeepesh** [comment]
@MVENKATESH786 Are you still on this?

**Comment by MVENKATESH786** [comment]
Yes, I’m still working on this.
