### ISSUE TITLE
Add a loading state UI. Replacing "Loading..." text

### ISSUE THREAD

**Issue by akadeepesh** [akadeepesh/OIBSIP#3]
In `pizza-delivery-app-client/pages/menu.tsx` line `111`. I'm returning div with text "Loading...".
Please return a loading UI there.

![image](https://github.com/user-attachments/assets/cbd4d58e-c0fa-4664-9270-d1a2900b9484)

Please stick to colors available in tailwind config file.

**Comment by MVENKATESH786** [comment]
I want to work on this please assign me to this issue.

**Comment by akadeepesh** [comment]
@MVENKATESH786 Assigned

**Comment by akadeepesh** [comment]
@MVENKATESH786 Are you still on this?

**Comment by nabanichowdhury** [comment]
@akadeepesh can you assign me this issue?

**Comment by akadeepesh** [comment]
go ahead @nabanichowdhury

**Comment by nabanichowdhury** [comment]
@akadeepesh  I am not being able to push my code in the branch I have created.

<img width="514" alt="image" src="https://github.com/user-attachments/assets/975c498d-5013-42d9-be00-5623dcf74cad">

Please grant the access

**Comment by akadeepesh** [comment]
You have to fork the repo first then make your changes to a branch. It will show you to make a PR on your repo to the main branch of this repo after you push your changes to the fork
